name: 打包测试1
on:
  workflow_dispatch:
    inputs:
      version:
        description: "打包"
        required: true
        type: boolean
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: 读取仓库
        uses: actions/checkout@v4

      - name: 安装 node
        uses: actions/setup-node@v4
        with:
          node-version: "23"
      - name: 添加软件源
        run: |
          sudo tee -a /etc/apt/sources.list <<< "deb http://cz.archive.ubuntu.com/ubuntu bionic main universe"
      - name: 导入公钥
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3B4FE6ACC0B21F32
      - name: 安装ubuntu依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - name: 安装 rust
        uses: dtolnay/rust-toolchain@stable

      - name: 安装 yarn
        run: npm install -g yarn

      - name: 安装依赖
        run: yarn install

      - name: 打包tauri
        uses: tauri-apps/tauri-action@v0.5.12

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: tauri-app-linux
          path: src-tauri/target/release/bundle/
